# Generated by Django 2.2.8 on 2020-01-24 01:17

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("coldemail", "0008_auto_20200122_2326"),
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driprecord", options={"ordering": ("runner", "root", "order")},
        ),
        migrations.AlterModelOptions(
            name="sendingrule", options={"ordering": ("runner", "index")},
        ),
        migrations.AddField(
            model_name="basecampaignrunner",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="basecampaignrunner",
            name="run_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name="driprecord", unique_together={("runner", "root", "order")},
        ),
    ]
