# Generated by Django 2.2.8 on 2020-02-01 00:27

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0003_auto_20200131_2343"),
    ]

    operations = [
        migrations.RemoveField(model_name="basecampaignrunner", name="published",),
        migrations.AddField(
            model_name="basecampaignrunner",
            name="is_removed_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now,
                monitor="is_removed",
                verbose_name="deleted at",
            ),
        ),
        migrations.AddField(
            model_name="basecampaignrunner",
            name="published_at",
            field=model_utils.fields.MonitorField(
                blank=True,
                default=None,
                monitor="status",
                null=True,
                when={"published"},
            ),
        ),
    ]
