# Generated by Django 2.2.8 on 2020-02-01 04:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_auto_20200201_0027"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basecampaignrunner",
            name="tracking_params",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
