# Generated by Django 2.2.8 on 2020-02-06 00:17

from django.db import migrations, models
import whoweb.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0005_auto_20200201_0442"),
    ]

    operations = [
        migrations.AddField(
            model_name="basecampaignrunner",
            name="public_id",
            field=models.CharField(
                default=whoweb.contrib.fields.random_public_id,
                editable=False,
                max_length=16,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
