# Generated by Django 2.2.8 on 2020-02-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0007_auto_20200206_0201"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simpledripcampaignrunner",
            name="open_credit_budget",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
