# Generated by Django 2.2.8 on 2020-02-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0008_auto_20200220_0041"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intervalcampaignrunner",
            name="max_sends",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total campaigns allowed for this manager.",
                null=True,
            ),
        ),
    ]
