# Generated by Django 2.2.8 on 2020-02-21 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0009_auto_20200220_0041"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simpledripcampaignrunner", name="preset_campaign_list",
        ),
    ]
