# Generated by Django 2.2.8 on 2020-02-24 22:01

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("coldemail", "0014_auto_20200224_1256"),
        ("campaigns", "0011_auto_20200220_1736"),
    ]

    operations = [
        migrations.AddField(
            model_name="basecampaignrunner",
            name="tags",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                force_lowercase=True,
                help_text="Enter a comma-separated tag string",
                to="coldemail.ColdEmailTagModel",
            ),
        ),
    ]
