# Generated by Django 2.2.8 on 2020-02-26 01:08

from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0012_basecampaignrunner_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basecampaignrunner",
            name="run_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="basecampaignrunner",
            name="tags",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                blank=True,
                force_lowercase=True,
                help_text="Enter a comma-separated tag string",
                to="coldemail.ColdEmailTagModel",
            ),
        ),
        migrations.AlterField(
            model_name="sendingrule",
            name="message_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="coldemail.CampaignMessageTemplate",
            ),
        ),
    ]
