# Generated by Django 2.2.8 on 2020-02-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_basecampaignrunner_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecampaignrunner',
            name='from_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
