# Generated by Django 2.2.8 on 2020-02-27 02:33

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0013_auto_20200225_1708"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basecampaignrunner",
            name="published_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="status", null=True, when={8}
            ),
        ),
    ]
