# Generated by Django 2.2.8 on 2020-03-12 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0015_basecampaignrunner_from_name"),
        ("campaigns", "0015_auto_20200303_1622"),
    ]

    operations = []
