# Generated by Django 2.2.8 on 2020-03-13 18:31

from django.db import migrations


def convert_seat_to_billing(apps, schema_editor):
    Model = apps.get_model("campaigns", "basecampaignrunner")
    for inst in Model.objects.filter(seat__isnull=False):
        inst.billing_seat = inst.seat.billing
        inst.save(update_fields=["billing_seat"])


def convert_billing_to_seat(apps, schema_editor):
    Model = apps.get_model("campaigns", "basecampaignrunner")
    for inst in Model.objects.filter(billing_seat__isnull=False):
        inst.seat = inst.billing_seat.seat
        inst.save(update_fields=["seat"])


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0017_basecampaignrunner_billing_seat"),
    ]

    operations = [
        migrations.RunPython(
            convert_seat_to_billing, reverse_code=convert_billing_to_seat
        ),
    ]
