# Generated by Django 2.2.19 on 2021-04-14 02:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0019_auto_20200521_1420"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="basecampaignrunner",
            managers=[("available_objects", django.db.models.manager.Manager()),],
        ),
        migrations.AlterModelManagers(
            name="intervalcampaignrunner",
            managers=[("available_objects", django.db.models.manager.Manager()),],
        ),
        migrations.AlterModelManagers(
            name="simpledripcampaignrunner",
            managers=[("available_objects", django.db.models.manager.Manager()),],
        ),
    ]
