# Generated by Django 2.2.19 on 2021-07-16 18:02

from django.db import migrations, models
import whoweb.campaigns.models.base


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0021_basecampaignrunner_saved_search"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basecampaignrunner",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "DRAFT"),
                    (2, "PENDING"),
                    (4, "PAUSED"),
                    (8, "PUBLISHED"),
                    (16, "RUNNING"),
                    (32, "SENDING"),
                    (128, "COMPLETE"),
                ],
                db_index=True,
                default=whoweb.campaigns.models.base.BaseCampaignRunner.CampaignRunnerStatusOptions(
                    0
                ),
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="sendingrule",
            name="trigger",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "DATETIME"), (1, "TIMEDELTA"), (2, "DELAY")],
                default=whoweb.campaigns.models.SendingRule.SendingRuleTriggerOptions(
                    2
                ),
            ),
        ),
    ]
