# Generated by Django 2.2.19 on 2021-10-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0025_auto_20210910_1826"),
    ]

    operations = [
        migrations.AddField(
            model_name="icebreakertemplate",
            name="is_global_default",
            field=models.NullBooleanField(default=None, unique=True),
        ),
    ]
