# Generated by Django 2.2.19 on 2021-10-09 00:31

from django.db import migrations, models
import django.db.models.deletion
import whoweb.campaigns.models.base


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0026_icebreakertemplate_is_global_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sendingrule",
            name="icebreaker_template",
            field=models.ForeignKey(
                blank=True,
                default=whoweb.campaigns.models.base.get_icebreaker_default,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campaigns.IcebreakerTemplate",
            ),
        ),
    ]
