# Generated by Django 2.2.6 on 2019-12-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounting", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="ledgerbalance",
            name="balance",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="amount",
            field=models.IntegerField(
                help_text="Amount for this entry.Debits are positive, and credits are negative."
            ),
        ),
    ]
