# Generated by Django 2.2.3 on 2019-09-12 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("payments", "0001_initial"),
        ("organizations", "0003_field_fix_and_editable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="billingaccountmember",
            name="seat",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billing",
                to="users.Seat",
                verbose_name="group seat",
            ),
        ),
        migrations.AddField(
            model_name="billingaccountmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments_billingaccountmember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="billingaccount",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organizations.Organization",
            ),
        ),
        migrations.AddField(
            model_name="billingaccount",
            name="seats",
            field=models.ManyToManyField(
                related_name="billing_account",
                through="payments.BillingAccountMember",
                to="users.Seat",
            ),
        ),
        migrations.AddField(
            model_name="billingaccount",
            name="users",
            field=models.ManyToManyField(
                related_name="payments_billingaccount",
                through="payments.BillingAccountMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
