# Generated by Django 2.2.6 on 2019-12-03 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("payments", "0001_squashed_0004_auto_20191106_0014")]

    operations = [
        migrations.CreateModel(
            name="WKPlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credits_per_enrich",
                    models.IntegerField(
                        default=5,
                        help_text="Number of credits charged for an enrich service call.",
                        verbose_name="Credits per Enrich",
                    ),
                ),
                (
                    "credits_per_work_email",
                    models.IntegerField(
                        default=100,
                        help_text="Number of credits charged for a service call returning any work emails.",
                        verbose_name="Credits per Work Derivation",
                    ),
                ),
                (
                    "credits_per_personal_email",
                    models.IntegerField(
                        default=300,
                        help_text="Number of credits charged for a service call returning any personal emails.",
                        verbose_name="Credits per Personal Derivation",
                    ),
                ),
                (
                    "credits_per_phone",
                    models.IntegerField(
                        default=400,
                        help_text="Number of credits charged for a service call returning any phone numbers.",
                        verbose_name="Credits per Phone Derivation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="billingaccount",
            name="plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.WKPlan",
            ),
        ),
    ]
