# Generated by Django 2.2.3 on 2019-09-17 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial"), ("payments", "0002_auto_20190912_2355")]

    operations = [
        migrations.AlterModelOptions(
            name="billingaccountmember",
            options={
                "verbose_name": "billing account member",
                "verbose_name_plural": "billing account members",
            },
        ),
        migrations.RemoveField(model_name="billingaccount", name="org"),
        migrations.AddField(
            model_name="billingaccount",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.Group",
            ),
        ),
    ]
