# Generated by Django 2.2.3 on 2019-09-10 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("payments", "0002_auto_20190910_0106")]

    operations = [
        migrations.AlterModelOptions(
            name="billingaccountmember",
            options={
                "verbose_name": "billing account seat",
                "verbose_name_plural": "billing account seats",
            },
        ),
        migrations.AlterField(
            model_name="billingaccountowner",
            name="organization_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.BillingAccountMember",
                verbose_name="billing account seat",
            ),
        ),
    ]
