# Generated by Django 2.2.8 on 2020-02-20 22:10

from django.db import migrations

from whoweb.contrib.fields import random_public_id


def gen_public_id(apps, schema_editor):
    MyModel = apps.get_model("payments", "wkplan")
    for row in MyModel.objects.all():
        row.public_id = random_public_id()
        row.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_wkplan_public_id"),
    ]

    operations = [
        migrations.RunPython(gen_public_id, reverse_code=migrations.RunPython.noop),
    ]
