# Generated by Django 2.2.8 on 2020-02-20 22:10
from django.db import migrations, models
import whoweb.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_auto_20200220_1410"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wkplan",
            name="public_id",
            field=models.CharField(
                default=whoweb.contrib.fields.random_public_id,
                editable=False,
                max_length=16,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
