# Generated by Django 2.2.8 on 2020-02-28 22:36

from django.db import migrations, models
import whoweb.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_auto_20200220_1410"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingaccount",
            name="public_id",
            field=models.CharField(
                default=whoweb.contrib.fields.random_public_id,
                editable=False,
                max_length=16,
                null=True,
                verbose_name="ID",
            ),
        ),
        migrations.AddField(
            model_name="billingaccountmember",
            name="public_id",
            field=models.CharField(
                default=whoweb.contrib.fields.random_public_id,
                editable=False,
                max_length=16,
                null=True,
                verbose_name="ID",
            ),
        ),
    ]
