# Generated by Django 2.2.8 on 2020-02-28 22:36

from django.db import migrations
from whoweb.contrib.fields import random_public_id


def gen_public_id(apps, schema_editor):
    BillingAccount = apps.get_model("payments", "billingaccount")
    for row in BillingAccount.objects.all():
        row.public_id = random_public_id()
        row.save(update_fields=["public_id"])
    BillingAccountMember = apps.get_model("payments", "billingaccountmember")
    for row in BillingAccountMember.objects.all():
        row.public_id = random_public_id()
        row.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_auto_20200228_1436"),
    ]

    operations = [
        migrations.RunPython(gen_public_id, reverse_code=migrations.RunPython.noop),
    ]
