# Generated by Django 2.2.8 on 2020-03-04 00:22

from django.db import migrations, models
import whoweb.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_auto_20200228_1436"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wkplan",
            options={
                "verbose_name": "credit plan",
                "verbose_name_plural": "credit plans",
            },
        ),
        migrations.AlterField(
            model_name="billingaccount",
            name="public_id",
            field=models.CharField(
                default=whoweb.contrib.fields.random_public_id,
                editable=False,
                help_text="Public ID of the object.",
                max_length=16,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="billingaccountmember",
            name="public_id",
            field=models.CharField(
                default=whoweb.contrib.fields.random_public_id,
                editable=False,
                help_text="Public ID of the object.",
                max_length=16,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="wkplan",
            name="public_id",
            field=models.CharField(
                default=whoweb.contrib.fields.random_public_id,
                editable=False,
                help_text="Public ID of the object.",
                max_length=16,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
