# Generated by Django 2.2.8 on 2020-03-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_wkplanpreset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wkplanpreset",
            name="stripe_plans",
            field=models.ManyToManyField(
                limit_choices_to={"active": True}, to="djstripe.Plan"
            ),
        ),
    ]
