# Generated by Django 2.2.8 on 2020-03-12 03:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_auto_20200310_1711"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingaccount",
            name="plan_history",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AlterField(
            model_name="billingaccount",
            name="plan",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.WKPlan",
            ),
        ),
    ]
