# Generated by Django 2.2.8 on 2020-03-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_auto_20200311_2013"),
    ]

    operations = [
        migrations.AddField(
            model_name="wkplan",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
    ]
