# Generated by Django 2.2.8 on 2020-03-12 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0013_wkplan_is_removed"),
    ]

    operations = [
        migrations.DeleteModel(name="WKPlanPreset",),
    ]
