# Generated by Django 2.2.8 on 2020-03-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0015_wkplanpreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="wkplanpreset",
            name="trial_days_allows",
            field=models.PositiveSmallIntegerField(default=14),
        ),
    ]
