# Generated by Django 2.2.8 on 2020-03-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0005_2_2"),
        ("payments", "0019_wkplanpresettag"),
    ]

    operations = [
        migrations.RemoveField(model_name="wkplanpreset", name="stripe_plans",),
        migrations.AddField(
            model_name="wkplanpreset",
            name="stripe_plans_monthly",
            field=models.ManyToManyField(
                limit_choices_to={"active": True},
                related_name="monthly_presets",
                to="djstripe.Plan",
            ),
        ),
        migrations.AddField(
            model_name="wkplanpreset",
            name="stripe_plans_yearly",
            field=models.ManyToManyField(
                limit_choices_to={"active": True},
                related_name="yearly_presets",
                to="djstripe.Plan",
            ),
        ),
    ]
