# Generated by Django 2.2.8 on 2020-03-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0020_auto_20200324_1820"),
    ]

    operations = [
        migrations.AddField(
            model_name="wkplanpreset",
            name="tag",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.DeleteModel(name="WKPlanPresetTag",),
    ]
