# Generated by Django 2.2.8 on 2020-03-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0022_wkplanpreset_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="wkplanpreset",
            name="marketing_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
