# Generated by Django 2.2.8 on 2020-03-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0023_wkplanpreset_marketing_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="wkplan",
            name="marketing_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
