# Generated by Django 2.2.8 on 2020-03-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0024_wkplan_marketing_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wkplanpreset",
            name="stripe_plans_monthly",
            field=models.ManyToManyField(
                limit_choices_to={"active": True, "interval": "month"},
                related_name="monthly_presets",
                to="djstripe.Plan",
            ),
        ),
        migrations.AlterField(
            model_name="wkplanpreset",
            name="stripe_plans_yearly",
            field=models.ManyToManyField(
                limit_choices_to={"active": True, "interval": "year"},
                related_name="yearly_presets",
                to="djstripe.Plan",
            ),
        ),
    ]
