# Generated by Django 2.2.8 on 2020-04-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0005_2_2"),
        ("payments", "0025_auto_20200330_1809"),
    ]

    operations = [
        migrations.AddField(
            model_name="wkplanpreset",
            name="defaults",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"active": True},
                related_name="_wkplanpreset_defaults_+",
                to="djstripe.Plan",
            ),
        ),
    ]
