# Generated by Django 2.2.8 on 2020-04-19 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0005_2_2"),
        ("payments", "0026_wkplanpreset_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiPlanSubscription",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("djstripe.subscription",),
        ),
        migrations.RemoveField(model_name="billingaccount", name="trial_credit_pool",),
        migrations.RemoveField(
            model_name="billingaccountmember", name="seat_trial_credits",
        ),
    ]
