# Generated by Django 2.2.10 on 2020-04-25 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0027_auto_20200418_2002"),
        ("users", "0019_auto_20200424_1748"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingaccount",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.Network",
            ),
        ),
        migrations.RenameField(
            model_name="billingaccount", old_name="group", new_name="network",
        ),
    ]
