# Generated by Django 2.2.10 on 2020-04-25 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0027_auto_20200418_2002"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billingaccount", old_name="group", new_name="network",
        ),
    ]
