# Generated by Django 2.2.10 on 2020-04-29 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0028_auto_20200425_1453"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billingaccount",
            options={
                "permissions": (
                    (
                        "change_membercredits",
                        "May allocate and revoke credits for all members.",
                    ),
                    (
                        "add_billingaccountmember",
                        "Add billing account member to billing account.",
                    ),
                    (
                        "view_billingaccountmember",
                        "View all billing account members in this billing account.",
                    ),
                    (
                        "delete_billingaccountmember",
                        "Delete billing account member from billing account.",
                    ),
                ),
                "verbose_name": "billing account",
                "verbose_name_plural": "billing accounts",
            },
        ),
    ]
