# Generated by Django 2.2.10 on 2020-06-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0030_auto_20200428_1907"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingaccount",
            name="customer_type",
            field=models.CharField(default="recruiter", max_length=50),
            preserve_default=False,
        ),
    ]
