# Generated by Django 2.2.10 on 2020-07-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0031_billingaccount_customer_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingaccount",
            name="customer_type",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
