apiVersion: v1
description: A Helm chart for deploying WhoWeb
icon: "https://sentry.io/_assets/logos/tornado-bd8724842aed9cee3a1fa08e30b75b4110970f25c34ce0f0797acf501fbae517.svg"
name: whoweb
version: 7.3.0
