apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "jx.derivation.fullname" . }}
  labels:
    chart: {{ template "jx.chart" .}}
  {{- if .Values.deployment.reloadOnEnvChange }}
  annotations:
    {{- if .Values.deployment.envConfigMapRef }}
    configmap.reloader.stakater.com/reload: "{{.Values.deployment.envConfigMapRef}},celeryd-config"
    {{- else }}
    configmap.reloader.stakater.com/reload: celeryd-config
    {{- end }}
    {{- if .Values.deployment.envSecretRef }}
    secret.reloader.stakater.com/reload: "{{.Values.deployment.envSecretRef}}"
    {{- end }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "jx.derivation.fullname" . }}
  replicas: 1
  strategy:
{{ toYaml .Values.deployment.strategy | indent 4 }}
  template:
    metadata:
      labels:
        app: {{ template "jx.derivation.fullname" . }}
    spec:
      terminationGracePeriodSeconds: {{ default 30 .Values.deployment.gracePeriod }}
      hostAliases:
      - ip: "10.10.0.2"
        hostnames:
        - "vm-mongo-cs-gce-01"
      - ip: "10.10.0.4"
        hostnames:
        - "vm-mongo-cs-gce-02"
      - ip: "10.10.0.7"
        hostnames:
        - "vm-mongo-cs-gce-03"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
          {{- range .Values.derivation.command }}
          - {{ . | quote }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            exec:
              command:
                - exit $(test $(date +%H) -eq 9 && echo 1 || echo 0)
            failureThreshold: 1
            initialDelaySeconds: 28800
            periodSeconds: 60
          env:
          - name: IMAGE
            value: {{ .Values.image.repository }}
          - name: REVISION
            value: {{ .Values.image.tag }}
          - name: ENVIRONMENT_NAME
            value: {{ .Release.Name }}
{{ toYaml .Values.derivation.env | indent 10 -}}
          envFrom:
          - configMapRef:
              name: {{ .Values.deployment.envConfigMapRef }}
          - secretRef:
              name: {{ .Values.deployment.envSecretRef }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
