# Generated by Django 2.2.8 on 2020-01-14 00:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import whoweb.contrib.postgres.fields
import whoweb.contrib.postgres.utils
import whoweb.search.models.embedded


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0011_searchexport_is_removed"),
        ("coldemail", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "status",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Created"),
                            (2, "Pending"),
                            (4, "Published"),
                            (8, "Paused"),
                        ],
                        db_index=True,
                        default=0,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                ("coldemail_id", models.CharField(max_length=100)),
                (
                    "is_removed_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="is_removed",
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "published_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        when={"published"},
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "origin",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "USER"), (2, "SYSTEM"), (3, "INTRO")]
                    ),
                ),
                ("results_fetched", models.DateTimeField()),
                (
                    "query",
                    whoweb.contrib.postgres.fields.EmbeddedModelField(
                        encoder=whoweb.contrib.postgres.utils.EmbeddedJSONEncoder,
                        model_container=whoweb.search.models.embedded.FilteredSearchQuery,
                        null=True,
                    ),
                ),
                (
                    "export",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="search.SearchExport",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="CampaignMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "status",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Created"),
                            (2, "Pending"),
                            (4, "Published"),
                            (8, "Paused"),
                        ],
                        db_index=True,
                        default=0,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                ("coldemail_id", models.CharField(max_length=100)),
                (
                    "is_removed_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="is_removed",
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "published_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        when={"published"},
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subject", models.TextField()),
                ("plain_content", models.TextField()),
                ("html_content", models.TextField()),
                ("editor", models.CharField(max_length=255)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="CampaignMessageTemplate",
            fields=[
                (
                    "campaignmessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="coldemail.CampaignMessage",
                    ),
                )
            ],
            options={"abstract": False},
            bases=("coldemail.campaignmessage",),
        ),
        migrations.CreateModel(
            name="SingleColdEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "status",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Created"),
                            (2, "Pending"),
                            (4, "Published"),
                            (8, "Paused"),
                        ],
                        db_index=True,
                        default=0,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                ("coldemail_id", models.CharField(max_length=100)),
                (
                    "is_removed_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="is_removed",
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "published_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        when={"published"},
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("from_name", models.CharField(max_length=255)),
                ("send_date", models.DateTimeField()),
                ("test", models.BooleanField(default=False)),
                ("use_credits_method", models.CharField(max_length=90)),
                ("views", models.PositiveIntegerField()),
                ("clicks", models.PositiveIntegerField()),
                ("optouts", models.PositiveIntegerField()),
                (
                    "message",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="coldemail.CampaignMessage",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="CampaignSend",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "status",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Created"),
                            (2, "Pending"),
                            (4, "Published"),
                            (8, "Paused"),
                        ],
                        db_index=True,
                        default=0,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                ("coldemail_id", models.CharField(max_length=100)),
                (
                    "is_removed_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="is_removed",
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "published_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        when={"published"},
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("from_name", models.CharField(max_length=255)),
                ("from_address", models.CharField(max_length=255)),
                ("send_time", models.DateTimeField(null=True)),
                ("sent", models.PositiveIntegerField(default=0)),
                ("views", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("unique_clicks", models.PositiveIntegerField(default=0)),
                ("unique_views", models.PositiveIntegerField(default=0)),
                ("optouts", models.PositiveIntegerField(default=0)),
                ("fetched", models.DateTimeField(null=True)),
                ("good", models.PositiveIntegerField(default=0)),
                ("start_time", models.CharField(max_length=255)),
                ("end_time", models.CharField(max_length=255)),
                (
                    "click_log",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "open_log",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "good_log",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "reply_log",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "campaign_list",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="coldemail.CampaignList",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="coldemail.CampaignMessage",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="CampaignEmailLookup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("web_id", models.CharField(max_length=160)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_lookup",
                        to="coldemail.CampaignSend",
                    ),
                ),
            ],
        ),
    ]
