# Generated by Django 2.2.8 on 2020-01-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "coldemail",
            "0002_campaignemaillookup_campaignlist_campaignmessage_campaignmessagetemplate_campaignsend_singlecoldemai",
        )
    ]

    operations = [
        migrations.AddIndex(
            model_name="campaignemaillookup",
            index=models.Index(
                fields=["campaign"], name="coldemail_c_campaig_aef637_idx"
            ),
        )
    ]
