# Generated by Django 2.2.8 on 2020-01-15 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("coldemail", "0003_auto_20200114_0148"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignemaillookup",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_lookups",
                to="coldemail.CampaignSend",
            ),
        ),
    ]
