# Generated by Django 2.2.8 on 2020-01-20 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coldemail", "0004_auto_20200115_0040"),
    ]

    operations = [
        migrations.RenameModel(old_name="CampaignSend", new_name="ColdCampaign",),
    ]
