# Generated by Django 2.2.8 on 2020-01-21 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20191217_0651"),
        ("coldemail", "0005_auto_20200120_2323"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coldcampaign", old_name="fetched", new_name="stats_fetched",
        ),
        migrations.AddField(
            model_name="campaignlist",
            name="seat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.Seat",
            ),
        ),
        migrations.AddField(
            model_name="campaignmessage",
            name="seat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.Seat",
            ),
        ),
        migrations.AddField(
            model_name="coldcampaign",
            name="seat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.Seat",
            ),
        ),
        migrations.AddField(
            model_name="singlecoldemail",
            name="seat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.Seat",
            ),
        ),
    ]
