# Generated by Django 2.2.8 on 2020-01-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coldemail", "0006_auto_20200121_0058"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignlist",
            name="origin",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "USER"), (2, "SYSTEM"), (3, "INTRO")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="campaignlist",
            name="results_fetched",
            field=models.DateTimeField(null=True),
        ),
    ]
