# Generated by Django 2.2.8 on 2020-01-31 00:25

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("coldemail", "0008_auto_20200122_2326"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignlist",
            name="published_at",
            field=model_utils.fields.MonitorField(
                blank=True,
                default=None,
                monitor="status",
                null=True,
                when={"published"},
            ),
        ),
        migrations.AlterField(
            model_name="campaignmessage",
            name="published_at",
            field=model_utils.fields.MonitorField(
                blank=True,
                default=None,
                monitor="status",
                null=True,
                when={"published"},
            ),
        ),
        migrations.AlterField(
            model_name="coldcampaign",
            name="published_at",
            field=model_utils.fields.MonitorField(
                blank=True,
                default=None,
                monitor="status",
                null=True,
                when={"published"},
            ),
        ),
        migrations.AlterField(
            model_name="singlecoldemail",
            name="published_at",
            field=model_utils.fields.MonitorField(
                blank=True,
                default=None,
                monitor="status",
                null=True,
                when={"published"},
            ),
        ),
    ]
