# Generated by Django 2.2.8 on 2020-02-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coldemail", "0009_auto_20200131_0025"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignmessage",
            name="editor",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
