# Generated by Django 2.2.8 on 2020-02-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coldemail", "0011_auto_20200206_0119"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singlecoldemail",
            name="clicks",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="singlecoldemail",
            name="optouts",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="singlecoldemail",
            name="views",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
