# Generated by Django 2.2.8 on 2020-02-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coldemail", "0012_auto_20200210_1622"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignlist",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
