# Generated by Django 2.2.8 on 2020-02-24 20:56

from django.db import migrations, models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ("coldemail", "0013_campaignlist_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColdEmailTagModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField()),
                (
                    "count",
                    models.IntegerField(
                        default=0,
                        help_text="Internal counter of how many times this tag is in use",
                    ),
                ),
                (
                    "protected",
                    models.BooleanField(
                        default=False,
                        help_text="Will not be deleted when the count reaches 0",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
                "unique_together": {("slug",)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AddField(
            model_name="campaignlist",
            name="tags",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                force_lowercase=True,
                help_text="Enter a comma-separated tag string",
                to="coldemail.ColdEmailTagModel",
            ),
        ),
        migrations.AddField(
            model_name="campaignmessage",
            name="tags",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                force_lowercase=True,
                help_text="Enter a comma-separated tag string",
                to="coldemail.ColdEmailTagModel",
            ),
        ),
        migrations.AddField(
            model_name="coldcampaign",
            name="tags",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                force_lowercase=True,
                help_text="Enter a comma-separated tag string",
                to="coldemail.ColdEmailTagModel",
            ),
        ),
        migrations.AddField(
            model_name="singlecoldemail",
            name="tags",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                force_lowercase=True,
                help_text="Enter a comma-separated tag string",
                to="coldemail.ColdEmailTagModel",
            ),
        ),
    ]
