# Generated by Django 2.2.8 on 2020-02-26 01:08

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("coldemail", "0014_auto_20200224_1256"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignlist",
            name="tags",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                blank=True,
                force_lowercase=True,
                help_text="Enter a comma-separated tag string",
                to="coldemail.ColdEmailTagModel",
            ),
        ),
        migrations.AlterField(
            model_name="campaignmessage",
            name="tags",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                blank=True,
                force_lowercase=True,
                help_text="Enter a comma-separated tag string",
                to="coldemail.ColdEmailTagModel",
            ),
        ),
        migrations.AlterField(
            model_name="coldcampaign",
            name="tags",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                blank=True,
                force_lowercase=True,
                help_text="Enter a comma-separated tag string",
                to="coldemail.ColdEmailTagModel",
            ),
        ),
        migrations.AlterField(
            model_name="singlecoldemail",
            name="tags",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                blank=True,
                force_lowercase=True,
                help_text="Enter a comma-separated tag string",
                to="coldemail.ColdEmailTagModel",
            ),
        ),
    ]
