# Generated by Django 2.2.8 on 2020-03-04 00:22

from django.db import migrations, models
import whoweb.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ("coldemail", "0016_auto_20200226_1833"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignlist",
            name="public_id",
            field=models.CharField(
                default=whoweb.contrib.fields.random_public_id,
                editable=False,
                help_text="Public ID of the object.",
                max_length=16,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="campaignmessage",
            name="public_id",
            field=models.CharField(
                default=whoweb.contrib.fields.random_public_id,
                editable=False,
                help_text="Public ID of the object.",
                max_length=16,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="coldcampaign",
            name="public_id",
            field=models.CharField(
                default=whoweb.contrib.fields.random_public_id,
                editable=False,
                help_text="Public ID of the object.",
                max_length=16,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="singlecoldemail",
            name="public_id",
            field=models.CharField(
                default=whoweb.contrib.fields.random_public_id,
                editable=False,
                help_text="Public ID of the object.",
                max_length=16,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
