# Generated by Django 2.2.8 on 2020-03-13 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0015_wkplanpreset"),
        ("coldemail", "0017_auto_20200303_1622"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignlist",
            name="billing_seat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.BillingAccountMember",
            ),
        ),
        migrations.AddField(
            model_name="campaignmessage",
            name="billing_seat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.BillingAccountMember",
            ),
        ),
        migrations.AddField(
            model_name="coldcampaign",
            name="billing_seat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.BillingAccountMember",
            ),
        ),
        migrations.AddField(
            model_name="singlecoldemail",
            name="billing_seat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.BillingAccountMember",
            ),
        ),
    ]
