# Generated by Django 2.2.8 on 2020-03-13 18:31

from django.db import migrations


def convert_seat_to_billing(model):
    def op(apps, schema):
        Model = apps.get_model("coldemail", model)
        for inst in Model.objects.filter(seat__isnull=False):
            inst.billing_seat = inst.seat.billing
            inst.save(update_fields=["billing_seat"])

    return op


def convert_billing_to_seat(model):
    def rev(apps, schema):
        Model = apps.get_model("coldemail", model)
        for inst in Model.objects.filter(billing_seat__isnull=False):
            inst.seat = inst.billing_seat.seat
            inst.save(update_fields=["seat"])

    return rev


class Migration(migrations.Migration):
    dependencies = [
        ("coldemail", "0018_auto_20200313_1131"),
    ]

    operations = [
        migrations.RunPython(
            convert_seat_to_billing("campaignlist"),
            reverse_code=convert_billing_to_seat("campaignlist"),
        ),
        migrations.RunPython(
            convert_seat_to_billing("campaignmessage"),
            reverse_code=convert_billing_to_seat("campaignmessage"),
        ),
        migrations.RunPython(
            convert_seat_to_billing("coldcampaign"),
            reverse_code=convert_billing_to_seat("coldcampaign"),
        ),
        migrations.RunPython(
            convert_seat_to_billing("singlecoldemail"),
            reverse_code=convert_billing_to_seat("singlecoldemail"),
        ),
    ]
