# Generated by Django 2.2.10 on 2020-05-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coldemail", "0019_auto_20200313_1131"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaignlist", old_name="published_at", new_name="published",
        ),
        migrations.RenameField(
            model_name="campaignmessage", old_name="published_at", new_name="published",
        ),
        migrations.RenameField(
            model_name="coldcampaign", old_name="published_at", new_name="published",
        ),
        migrations.RenameField(
            model_name="singlecoldemail", old_name="published_at", new_name="published",
        ),
    ]
