# Generated by Django 2.2.10 on 2020-07-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coldemail", "0020_auto_20200521_1420"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignemaillookup",
            name="web_id",
            field=models.CharField(max_length=255),
        ),
    ]
