# Generated by Django 2.2.19 on 2021-07-02 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("coldemail", "0021_auto_20200706_1326"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignlist",
            name="billing_seat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.BillingAccountMember",
            ),
        ),
        migrations.AlterField(
            model_name="campaignmessage",
            name="billing_seat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.BillingAccountMember",
            ),
        ),
        migrations.AlterField(
            model_name="coldcampaign",
            name="billing_seat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.BillingAccountMember",
            ),
        ),
        migrations.AlterField(
            model_name="singlecoldemail",
            name="billing_seat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.BillingAccountMember",
            ),
        ),
    ]
