# Generated by Django 2.2.19 on 2021-07-27 19:46

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("coldemail", "0023_auto_20210716_1102"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="singlecoldemail", name="use_credits_method",
        ),
        migrations.AlterField(
            model_name="campaignlist",
            name="is_removed_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now,
                editable=False,
                monitor="is_removed",
                verbose_name="deleted at",
            ),
        ),
        migrations.AlterField(
            model_name="campaignmessage",
            name="is_removed_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now,
                editable=False,
                monitor="is_removed",
                verbose_name="deleted at",
            ),
        ),
        migrations.AlterField(
            model_name="coldcampaign",
            name="is_removed_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now,
                editable=False,
                monitor="is_removed",
                verbose_name="deleted at",
            ),
        ),
        migrations.AlterField(
            model_name="singlecoldemail",
            name="from_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="singlecoldemail",
            name="is_removed_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now,
                editable=False,
                monitor="is_removed",
                verbose_name="deleted at",
            ),
        ),
        migrations.AlterField(
            model_name="singlecoldemail",
            name="send_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
