# Generated by Django 2.2.3 on 2019-08-14 00:03

from django.db import migrations, models
import functools
import model_utils.fields
import whoweb.contrib.postgres.fields


class Migration(migrations.Migration):

    dependencies = [("exports", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="searchexport",
            name="columns",
            field=whoweb.contrib.postgres.fields.ChoiceArrayField(
                base_field=models.IntegerField(
                    choices=[
                        (0, "invitekey"),
                        (1, "First Name"),
                        (2, "Last Name"),
                        (3, "Title"),
                        (4, "Company"),
                        (5, "Industry"),
                        (6, "City"),
                        (7, "State"),
                        (8, "Country"),
                        (9, "Profile URL"),
                        (10, "Experience"),
                        (11, "Education"),
                        (12, "Skills"),
                        (13, "Email"),
                        (14, "Email Grade"),
                        (15, "LinkedIn URL"),
                        (16, "Phone Number"),
                        (17, "Additional Emails"),
                        (18, "Facebook"),
                        (19, "Twitter"),
                        (20, "AngelList"),
                        (21, "Google Plus"),
                        (22, "Google Profile"),
                        (23, "Quora"),
                        (24, "GitHub"),
                        (25, "BitBucket"),
                        (26, "StackExchange"),
                        (27, "Flickr"),
                        (28, "YouTube"),
                        (29, "domain"),
                        (30, "mxdomain"),
                    ]
                ),
                default=functools.partial(
                    list,
                    *([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],),
                    **{}
                ),
                editable=False,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="searchexport",
            name="sent_at",
            field=model_utils.fields.MonitorField(
                default=None,
                editable=False,
                monitor="sent",
                null=True,
                verbose_name="sent at",
            ),
        ),
    ]
