# Generated by Django 2.2.3 on 2019-08-15 19:42

from django.db import migrations
import whoweb.contrib.postgres.fields
import whoweb.search.models


class Migration(migrations.Migration):

    dependencies = [("exports", "0002_auto_20190814_0003")]

    operations = [
        migrations.AlterField(
            model_name="searchexport",
            name="query",
            field=whoweb.contrib.postgres.fields.EmbeddedModelField(
                default=whoweb.search.models.FilteredSearchQuery,
                model_container=whoweb.search.models.FilteredSearchQuery,
            ),
        )
    ]
