# Generated by Django 2.2.3 on 2019-09-12 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0001_squashed_0003_auto_20190912_0026")]

    operations = [
        migrations.AlterModelOptions(
            name="seat",
            options={"verbose_name": "seat", "verbose_name_plural": "seats"},
        )
    ]
