# Generated by Django 2.2.6 on 2019-11-06 00:14

from django.db import migrations
import organizations.fields


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="slug",
            field=organizations.fields.SlugField(
                editable=True,
                help_text="The name in all lowercase, suitable for URL identification",
                max_length=200,
                populate_from="name",
                unique=True,
            ),
        )
    ]
