# Generated by Django 2.2.3 on 2019-08-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0002_auto_20190819_2258")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "A user with that email already exists."},
                help_text="Required. Verification handled in Admin>Accounts>Email addresses",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        )
    ]
