# Generated by Django 2.2.6 on 2019-11-07 01:35
from django.db import migrations
import os


class Migration(migrations.Migration):

    dependencies = [("users", "0002_auto_20191106_0014")]

    def generate_superuser(apps, schema_editor):
        from django.contrib.auth import get_user_model

        User = get_user_model()

        DJANGO_SU_NAME = os.environ.get("DJANGO_SU_NAME")
        DJANGO_SU_EMAIL = os.environ.get("DJANGO_SU_EMAIL")
        DJANGO_SU_PASSWORD = os.environ.get("DJANGO_SU_PASSWORD")
        superuser = User.objects.create_superuser(
            username=DJANGO_SU_NAME, email=DJANGO_SU_EMAIL, password=DJANGO_SU_PASSWORD
        )

        superuser.save()

    operations = [migrations.RunPython(generate_superuser)]
