# Generated by Django 2.2.8 on 2019-12-13 22:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_cryptography.fields
import model_utils.fields
import whoweb.users.models.group


class Migration(migrations.Migration):

    dependencies = [("users", "0003_auto_20191107_0135")]

    operations = [
        migrations.CreateModel(
            name="OrganizationCredentials",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default=whoweb.users.models.group.make_key,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "secret",
                    django_cryptography.fields.encrypt(
                        models.CharField(
                            default=whoweb.users.models.group.make_secret, max_length=64
                        )
                    ),
                ),
                ("test_key", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="users.Group",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credentials",
                        to="users.Seat",
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
