# Generated by Django 2.2.3 on 2019-09-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0003_auto_20190819_2316")]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="credits",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="trial_credits",
            field=models.IntegerField(default=0),
        ),
    ]
