# Generated by Django 2.2.3 on 2019-09-10 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0004_auto_20190909_2210")]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="credits"),
        migrations.RemoveField(model_name="userprofile", name="trial_credits"),
    ]
