# Generated by Django 2.2.8 on 2019-12-17 05:36

import whoweb.contrib.fields
from django.db import migrations
import whoweb.contrib.fields


class Migration(migrations.Migration):

    dependencies = [("users", "0006_organizationcredentials_created_by")]

    operations = [
        migrations.RenameModel(
            old_name="OrganizationCredentials", new_name="DeveloperKey"
        ),
        migrations.AlterModelOptions(
            name="group",
            options={
                "permissions": (
                    ("add_developerkeys", "May add credentials for this organization"),
                    ("add_seat", "May add seats to this organization"),
                ),
                "verbose_name": "network",
                "verbose_name_plural": "networks",
            },
        ),
        migrations.AlterField(
            model_name="group",
            name="id",
            field=contrib.fields.ObscuredAutoField(
                prefix="ntw", primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="seat",
            name="id",
            field=contrib.fields.ObscuredAutoField(
                prefix="seat", primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=whoweb.contrib.fields.ObscuredAutoField(
                prefix="usr", primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
