# Generated by Django 2.2.8 on 2019-12-17 05:37

import contrib.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0007_auto_20191217_0536")]

    operations = [
        migrations.AlterField(
            model_name="developerkey",
            name="id",
            field=contrib.fields.ObscuredAutoField(
                prefix="dev", primary_key=True, serialize=False, verbose_name="ID"
            ),
        )
    ]
