# Generated by Django 2.2.8 on 2019-12-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0008_auto_20191217_0537")]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "permissions": (
                    ("add_developerkeys", "May add credentials for this organization"),
                    ("add_seats", "May add seats to this organization"),
                ),
                "verbose_name": "network",
                "verbose_name_plural": "networks",
            },
        )
    ]
