# Generated by Django 2.2.8 on 2019-12-17 06:51

import whoweb.contrib.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0009_auto_20191217_0601")]

    operations = [
        migrations.AlterField(
            model_name="developerkey",
            name="id",
            field=contrib.fields.ObscuredAutoField(
                prefix="dk", primary_key=True, serialize=False, verbose_name="ID"
            ),
        )
    ]
