# Generated by Django 2.2.8 on 2020-02-06 00:04

from django.db import migrations
from whoweb.contrib.fields import random_public_id


def gen_public_id(model):
    def _gen_public_id(apps, schema_editor):
        MyModel = apps.get_model("users", model)
        for row in MyModel.objects.all():
            row.public_id = random_public_id()
            row.save(update_fields=["public_id"])

    return _gen_public_id


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_auto_20200206_0002"),
    ]

    operations = [
        migrations.RunPython(
            gen_public_id("DeveloperKey"), reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            gen_public_id("Group"), reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            gen_public_id("Seat"), reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            gen_public_id("User"), reverse_code=migrations.RunPython.noop
        ),
    ]
