# Generated by Django 2.2.8 on 2020-02-06 00:04

from django.db import migrations, models
from whoweb.contrib.fields import random_public_id


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_auto_20200206_0004"),
    ]

    operations = [
        migrations.AlterField(
            model_name="developerkey",
            name="public_id",
            field=models.CharField(
                default=random_public_id,
                editable=False,
                max_length=16,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="public_id",
            field=models.CharField(
                default=random_public_id,
                editable=False,
                max_length=16,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="seat",
            name="public_id",
            field=models.CharField(
                default=random_public_id,
                editable=False,
                max_length=16,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="public_id",
            field=models.CharField(
                default=random_public_id,
                editable=False,
                max_length=16,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
