# Generated by Django 2.2.8 on 2020-02-21 17:14

from django.db import migrations


def move_ids(apps, schema_editor):
    User = apps.get_model("users", "User")
    UserProfile = apps.get_model("users", "UserProfile")
    for user in User.objects.all():
        try:
            user.profile.public_id = user.public_id
            user.profile.save()
        except UserProfile.DoesNotExist:
            continue


def revert_ids(apps, schema_editor):
    UserProfile = apps.get_model("users", "UserProfile")
    for profile in UserProfile.objects.all():
        profile.user.public_id = profile.public_id
        profile.user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_auto_20200221_0914"),
    ]

    operations = [migrations.RunPython(move_ids, reverse_code=revert_ids)]
