# Generated by Django 2.2.8 on 2020-02-21 17:14

from django.db import migrations, models
import whoweb.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_auto_20200221_0914"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="public_id",),
        migrations.AlterField(
            model_name="userprofile",
            name="public_id",
            field=models.CharField(
                default=whoweb.contrib.fields.random_public_id,
                editable=False,
                max_length=16,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
