# Generated by Django 2.2.8 on 2020-03-04 00:22

from django.db import migrations, models
import whoweb.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_auto_20200221_0914"),
    ]

    operations = [
        migrations.AlterField(
            model_name="developerkey",
            name="public_id",
            field=models.CharField(
                default=whoweb.contrib.fields.random_public_id,
                editable=False,
                help_text="Public ID of the object.",
                max_length=16,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="public_id",
            field=models.CharField(
                default=whoweb.contrib.fields.random_public_id,
                editable=False,
                help_text="Public ID of the object.",
                max_length=16,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="seat",
            name="public_id",
            field=models.CharField(
                default=whoweb.contrib.fields.random_public_id,
                editable=False,
                help_text="Public ID of the object.",
                max_length=16,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="public_id",
            field=models.CharField(
                default=whoweb.contrib.fields.random_public_id,
                editable=False,
                help_text="Public ID of the object.",
                max_length=16,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
