# Generated by Django 2.2.10 on 2020-04-25 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_auto_20200303_1622"),
    ]

    operations = [
        migrations.RenameField(
            model_name="developerkey", old_name="group", new_name="network",
        ),
    ]
