# Generated by Django 2.2.10 on 2020-04-25 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_auto_20200303_1622"),
    ]

    operations = [
        migrations.RenameModel(old_name="group", new_name="network"),
        migrations.AlterField(
            model_name="developerkey",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credentials",
                to="users.Network",
            ),
        ),
        migrations.AlterField(
            model_name="groupowner",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to="users.Network",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="users",
            field=models.ManyToManyField(
                related_name="users_network",
                through="users.Seat",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="seat",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_users",
                to="users.Network",
            ),
        ),
    ]
