# Generated by Django 2.2.10 on 2020-04-25 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_auto_20200424_1748"),
    ]

    operations = [
        migrations.RenameField(
            model_name="developerkey", old_name="group", new_name="network",
        )
    ]
