# Generated by Django 2.2.10 on 2020-07-03 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_auto_20200428_1907"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "permissions": (
                    ("add_billing", "May add billing accounts in this organization"),
                    (
                        "add_developerkeys",
                        "May add API credentials for this organization",
                    ),
                    (
                        "view_developerkeys",
                        "May view all API credentials in this organization",
                    ),
                    (
                        "delete_developerkeys",
                        "May delete API credentials from this organization",
                    ),
                    ("add_seats", "May add seats to this organization"),
                    ("view_seats", "May view all seats in this organization"),
                    ("delete_seats", "May delete seats from this organization"),
                ),
                "verbose_name": "network",
                "verbose_name_plural": "networks",
            },
        ),
    ]
