# Generated by Django 2.2.10 on 2021-02-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_networkinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="xperweb_id",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
    ]
