# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  pullPolicy: IfNotPresent
  repository:
  tag:
nameOverride: "xperweb-celery"
deployment:
  envConfigMapRef: "xperweb-config"
  envSecretRef: "xperweb-secrets"
  reloadOnEnvChange: 1
  command: ["/usr/bin/supervisord"]
  env:
  - name: CELERY_WORKER_ARGS
    value: "-Q=celery"
  strategy:
    type: Recreate
  gracePeriod: 180
beat:
  replicas: 1
  name: "beat"
  args: [ "sleep 30; echo 'Starting Celery Beat'; python2.7 -m celery -A xperweb.tasks beat",]
derivation:
  replicas: 1
  name: "derivation"
  command: ["/usr/bin/supervisord"]
  env:
  - name: CELERY_WORKER_ARGS
    value: "-Q=derivation -P gevent -c 250"
resources:
  requests:
    cpu: "1"
    memory: "124Mi"
  limits:
    cpu: "8"
    memory: "16Gi"
