apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "jx.fullname" . }}-celery
  annotations:
    chart: {{ template "jx.chart" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "jx.fullname" . }}-celery
  minReplicas: {{ default 1 .Values.celery.hpa.minReplicas }}
  maxReplicas: {{ default 1 .Values.celery.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ default 100 .Values.celery.hpa.cpu }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ default 100 .Values.celery.hpa.memory }}
