apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "jx.fullname" . }}
  labels:
    chart: {{ template "jx.chart" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
        - {{ template "ingress.url" . }}
      secretName: {{ .Values.global.tlsSecretName }}
  rules:
  - host: {{ template "ingress.url" . }}
    http:
      paths:
      - path: {{ .Values.service.paths }}
        backend:
          serviceName: {{ .Values.service.name }}
          servicePort: {{ .Values.service.externalPort }}
