apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    chart: {{ template "jx.chart" . }}
  {{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity | default "None" }}
  ports:
  {{- range $name, $p := .Values.service.ports }}
  - name: {{ $name | quote }}
    port: {{ $p.port }}
    targetPort: {{ $p.targetPort }}
    {{- if $p.nodePort }}
    nodePort: {{ $p.nodePort }}
    {{- end }}
    protocol: TCP
  {{- end }}
  selector:
    app: {{ template "jx.fullname" . }}
