#!/bin/bash

set -o errexit
set -o nounset

export CONN_MAX_AGE=0
celery flower \
    --app=config.celery_app \
    --url_prefix=flower \
    --broker="${CELERY_BROKER_URL}" \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
