# Generated by Django 2.2.6 on 2019-11-06 00:16

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import functools
import model_utils.fields
import uuid
import whoweb.contrib.fields
import whoweb.contrib.postgres.fields
import whoweb.contrib.postgres.utils
import whoweb.search.models.embedded


class Migration(migrations.Migration):

    initial = True

    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="ExportOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "webhooks",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(), default=list, size=None
                    ),
                ),
                ("format", models.CharField(default="nested", max_length=255)),
            ],
            options={"managed": False},
        ),
        migrations.CreateModel(
            name="FilteredSearchFilterElement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field", models.CharField(max_length=255)),
                ("value", django.contrib.postgres.fields.jsonb.JSONField()),
                ("truth", models.BooleanField(default=True)),
            ],
            options={"managed": False},
        ),
        migrations.CreateModel(
            name="FilteredSearchFilters",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("limit", models.IntegerField(null=True)),
                ("skip", models.IntegerField(default=0, null=True)),
                (
                    "required",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=whoweb.contrib.postgres.fields.EmbeddedModelField(
                            default=whoweb.search.models.embedded.FilteredSearchFilterElement,
                            encoder=whoweb.contrib.postgres.utils.EmbeddedJSONEncoder,
                            model_container=whoweb.search.models.embedded.FilteredSearchFilterElement,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "desired",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=whoweb.contrib.postgres.fields.EmbeddedModelField(
                            default=whoweb.search.models.embedded.FilteredSearchFilterElement,
                            encoder=whoweb.contrib.postgres.utils.EmbeddedJSONEncoder,
                            model_container=whoweb.search.models.embedded.FilteredSearchFilterElement,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "profiles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=300),
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={"managed": False},
        ),
        migrations.CreateModel(
            name="FilteredSearchQuery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=36, null=True)),
                (
                    "filters",
                    whoweb.contrib.postgres.fields.EmbeddedModelField(
                        default=whoweb.search.models.embedded.FilteredSearchFilters,
                        encoder=whoweb.contrib.postgres.utils.EmbeddedJSONEncoder,
                        model_container=whoweb.search.models.embedded.FilteredSearchFilters,
                    ),
                ),
                (
                    "defer",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("contact", "contact"),
                                ("company_counts", "company_counts"),
                                ("degree_levels", "degree_levels"),
                            ],
                            max_length=50,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                ("with_invites", models.BooleanField(default=False)),
                (
                    "contact_filters",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("work", "work"),
                                ("personal", "personal"),
                                ("social", "social"),
                                ("phone", "phone"),
                                ("profile", "profile"),
                            ],
                            max_length=50,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "export",
                    whoweb.contrib.postgres.fields.EmbeddedModelField(
                        default=whoweb.search.models.embedded.ExportOptions,
                        encoder=whoweb.contrib.postgres.utils.EmbeddedJSONEncoder,
                        model_container=whoweb.search.models.embedded.ExportOptions,
                    ),
                ),
            ],
            options={"managed": False},
        ),
        migrations.CreateModel(
            name="MXDomain",
            fields=[
                (
                    "domain",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "mxs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        default=list,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScrollSearch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("scroll_key", models.UUIDField(default=uuid.uuid4)),
                (
                    "scroll_key_modified",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="scroll_key"
                    ),
                ),
                ("page_size", models.IntegerField(default=300)),
                ("query_hash", models.CharField(max_length=255)),
                ("total", models.IntegerField(default=None, null=True)),
                (
                    "query",
                    whoweb.contrib.postgres.fields.EmbeddedModelField(
                        default=whoweb.search.models.embedded.FilteredSearchQuery,
                        encoder=whoweb.contrib.postgres.utils.EmbeddedJSONEncoder,
                        model_container=whoweb.search.models.embedded.FilteredSearchQuery,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="SearchExport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "query",
                    whoweb.contrib.postgres.fields.EmbeddedModelField(
                        default=whoweb.search.models.embedded.FilteredSearchQuery,
                        encoder=whoweb.contrib.postgres.utils.EmbeddedJSONEncoder,
                        model_container=whoweb.search.models.embedded.FilteredSearchQuery,
                    ),
                ),
                (
                    "validation_list_id",
                    models.CharField(editable=False, max_length=50, null=True),
                ),
                (
                    "columns",
                    whoweb.contrib.postgres.fields.ChoiceArrayField(
                        base_field=models.IntegerField(
                            choices=[
                                (0, "invitekey"),
                                (1, "First Name"),
                                (2, "Last Name"),
                                (3, "Title"),
                                (4, "Company"),
                                (5, "Industry"),
                                (6, "City"),
                                (7, "State"),
                                (8, "Country"),
                                (9, "Profile URL"),
                                (10, "Experience"),
                                (11, "Education"),
                                (12, "Skills"),
                                (13, "Email"),
                                (14, "Email Grade"),
                                (15, "LinkedIn URL"),
                                (16, "Phone Number"),
                                (17, "Additional Emails"),
                                (18, "Facebook"),
                                (19, "Twitter"),
                                (20, "AngelList"),
                                (21, "Google Plus"),
                                (22, "Google Profile"),
                                (23, "Quora"),
                                (24, "GitHub"),
                                (25, "BitBucket"),
                                (26, "StackExchange"),
                                (27, "Flickr"),
                                (28, "YouTube"),
                                (29, "domain"),
                                (30, "mxdomain"),
                            ]
                        ),
                        default=functools.partial(
                            list,
                            *(
                                [
                                    1,
                                    2,
                                    3,
                                    4,
                                    5,
                                    6,
                                    7,
                                    8,
                                    9,
                                    10,
                                    11,
                                    12,
                                    13,
                                    14,
                                    15,
                                    16,
                                    17,
                                ],
                            ),
                            **{}
                        ),
                        editable=False,
                        size=None,
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[
                            (0, "Created"),
                            (2, "Pages Running"),
                            (4, "Pages Complete"),
                            (8, "Awaiting External Validation"),
                            (16, "Validation Complete"),
                            (32, "Post Processing Hooks Done"),
                            (128, "Export Complete"),
                        ],
                        db_index=True,
                        default=0,
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                ("sent", models.CharField(editable=False, max_length=255)),
                (
                    "sent_at",
                    model_utils.fields.MonitorField(
                        default=None,
                        editable=False,
                        monitor="sent",
                        null=True,
                        verbose_name="sent at",
                    ),
                ),
                ("progress_counter", models.IntegerField(default=0)),
                ("target", models.IntegerField(default=0)),
                ("charged", models.IntegerField(default=0)),
                ("refunded", models.IntegerField(default=0)),
                ("notify", models.BooleanField(default=False)),
                ("charge", models.BooleanField(default=False)),
                ("uploadable", models.BooleanField(default=False, editable=False)),
                ("on_trial", models.BooleanField(default=False)),
                (
                    "scroll",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="search.ScrollSearch",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.Seat"
                    ),
                ),
                ("valid_count", models.IntegerField(null=True)),
            ],
            options={"verbose_name": "export"},
        ),
        migrations.CreateModel(
            name="SearchExportPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "data",
                    whoweb.contrib.fields.CompressedBinaryJSONField(
                        editable=True, null=True
                    ),
                ),
                ("page_num", models.PositiveIntegerField()),
                (
                    "working_data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        editable=False, null=True
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("limit", models.IntegerField(null=True)),
                (
                    "export",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="search.SearchExport",
                    ),
                ),
            ],
            options={
                "ordering": ["export", "page_num"],
                "unique_together": {("export", "page_num")},
            },
        ),
        migrations.CreateModel(
            name="ScrollSearchPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("page_number", models.IntegerField()),
                ("key_used", models.CharField(max_length=64)),
                (
                    "results",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255, null=True),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "scroll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="search.ScrollSearch",
                    ),
                ),
            ],
            options={
                "ordering": ["scroll", "page_number"],
                "unique_together": {("scroll", "page_number")},
            },
        ),
    ]
