# Generated by Django 2.2.3 on 2019-08-15 19:42

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
import whoweb.contrib.postgres.fields
import whoweb.search.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FilteredSearchFilterElement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field", models.CharField(max_length=255)),
                ("value", django.contrib.postgres.fields.jsonb.JSONField()),
                ("truth", models.BooleanField(default=True)),
            ],
            options={"managed": False},
        ),
        migrations.CreateModel(
            name="FilteredSearchFilters",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("limit", models.IntegerField(null=True)),
                ("skip", models.IntegerField(default=0, null=True)),
                (
                    "required",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=whoweb.contrib.postgres.fields.EmbeddedModelField(
                            default=whoweb.search.models.FilteredSearchFilterElement,
                            model_container=whoweb.search.models.FilteredSearchFilterElement,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "desired",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=whoweb.contrib.postgres.fields.EmbeddedModelField(
                            default=whoweb.search.models.FilteredSearchFilterElement,
                            model_container=whoweb.search.models.FilteredSearchFilterElement,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "profiles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=300),
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={"managed": False},
        ),
        migrations.CreateModel(
            name="FilteredSearchQuery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=36, null=True)),
                (
                    "filters",
                    whoweb.contrib.postgres.fields.EmbeddedModelField(
                        default=whoweb.search.models.FilteredSearchFilters,
                        model_container=whoweb.search.models.FilteredSearchFilters,
                    ),
                ),
                (
                    "defer",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("contact", "contact"),
                                ("company_counts", "company_counts"),
                                ("degree_levels", "degree_levels"),
                            ],
                            max_length=50,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                ("with_invites", models.BooleanField(default=False)),
                (
                    "contact_filters",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("work", "work"),
                                ("personal", "personal"),
                                ("social", "social"),
                                ("phone", "phone"),
                                ("profile", "profile"),
                            ],
                            max_length=50,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={"managed": False},
        ),
        migrations.CreateModel(
            name="ScrollKey",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ScrollSearch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("page_size", models.IntegerField(default=300)),
                ("filters", django.contrib.postgres.fields.jsonb.JSONField()),
                ("query_hash", models.CharField(max_length=255)),
                ("total", models.IntegerField(null=True)),
                (
                    "scroll_key",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="search.ScrollKey",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ScrollSearchPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("page_number", models.IntegerField()),
                ("key_used", models.CharField(max_length=64)),
                (
                    "results",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255, null=True),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "scroll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="search.ScrollSearch",
                    ),
                ),
            ],
            options={
                "ordering": ["page_number"],
                "unique_together": {("scroll", "page_number")},
            },
        ),
    ]
