# Generated by Django 2.2.3 on 2019-08-15 20:10

from django.db import migrations
import whoweb.contrib.postgres.fields
import whoweb.search.models


class Migration(migrations.Migration):

    dependencies = [("search", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="scrollsearch", name="filters"),
        migrations.AddField(
            model_name="scrollsearch",
            name="query",
            field=whoweb.contrib.postgres.fields.EmbeddedModelField(
                default=whoweb.search.models.FilteredSearchQuery,
                model_container=whoweb.search.models.FilteredSearchQuery,
            ),
        ),
    ]
