# Generated by Django 2.2.3 on 2019-09-12 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("users", "0001_initial"), ("search", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="searchexport",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.Seat"
            ),
        ),
        migrations.AddField(
            model_name="scrollsearchpage",
            name="scroll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="search.ScrollSearch",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="searchexportpage", unique_together={("export", "page_num")}
        ),
        migrations.AlterUniqueTogether(
            name="scrollsearchpage", unique_together={("scroll", "page_number")}
        ),
    ]
