# Generated by Django 2.2.3 on 2019-08-19 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("search", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="searchexport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="scrollsearchpage",
            name="scroll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="search.ScrollSearch",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="searchexportpage", unique_together={("export", "page_num")}
        ),
        migrations.AlterUniqueTogether(
            name="scrollsearchpage", unique_together={("scroll", "page_number")}
        ),
    ]
