# Generated by Django 2.2.3 on 2019-09-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("search", "0002_auto_20190912_2355")]

    operations = [
        migrations.AddField(
            model_name="searchexport",
            name="valid_count",
            field=models.IntegerField(default=0),
        )
    ]
