# Generated by Django 2.2.3 on 2019-08-29 23:45

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [("search", "0002_auto_20190819_2234")]

    operations = [
        migrations.CreateModel(
            name="ExportOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "webhooks",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(), default=list, size=None
                    ),
                ),
                ("format", models.CharField(default="nested", max_length=255)),
            ],
            options={"managed": False},
        ),
        migrations.CreateModel(
            name="MXDomain",
            fields=[
                (
                    "domain",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "mxs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        default=[],
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="searchexport",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[(0, "dummy")],
                db_index=True,
                default=0,
                max_length=100,
                no_check_for_status=True,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="searchexportpage",
            name="working_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                editable=False, null=True
            ),
        ),
    ]
