# Generated by Django 2.2.6 on 2019-11-14 23:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("search", "0002_auto_20191114_0222")]

    operations = [
        migrations.AlterField(
            model_name="searchexport",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Created"),
                    (2, "Pages Running"),
                    (4, "Pages Complete"),
                    (8, "Awaiting External Validation"),
                    (16, "Validation Complete"),
                    (32, "Post Processing Hooks Done"),
                    (128, "Export Complete"),
                ],
                db_index=True,
                default=0,
                max_length=100,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="searchexport",
            name="uuid",
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4),
        ),
    ]
