# Generated by Django 2.2.3 on 2019-09-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("search", "0003_searchexport_valid_count")]

    operations = [
        migrations.AlterField(
            model_name="searchexport",
            name="valid_count",
            field=models.IntegerField(null=True),
        )
    ]
