# Generated by Django 2.2.3 on 2019-09-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("search", "0004_auto_20190829_2345")]

    operations = [
        migrations.AddField(
            model_name="searchexport",
            name="charged",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="searchexport",
            name="refunded",
            field=models.IntegerField(default=0),
        ),
    ]
