# Generated by Django 2.2.6 on 2019-11-20 22:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_results", "0004_auto_20190516_0412"),
        ("search", "0004_auto_20191119_2317"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scrollsearch", options={"verbose_name_plural": "Scrolling searches"}
        ),
        migrations.AddField(
            model_name="searchexportpage",
            name="derivation_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_celery_results.TaskResult",
            ),
        ),
        migrations.AlterField(
            model_name="searchexportpage",
            name="working_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, editable=False, null=True
            ),
        ),
    ]
