# Generated by Django 2.2.6 on 2019-11-06 00:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("search", "0004_auto_20190918_0025")]

    operations = [
        migrations.AlterField(
            model_name="searchexport",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        )
    ]
