# Generated by Django 2.2.6 on 2019-11-20 22:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0004_auto_20191119_2317"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scrollsearch", options={"verbose_name_plural": "Scrolling searches"}
        ),
        migrations.AlterField(
            model_name="searchexportpage",
            name="working_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, editable=False, null=True
            ),
        ),
    ]
