# Generated by Django 2.2.3 on 2019-09-10 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("search", "0005_auto_20190909_2210")]

    operations = [
        migrations.AlterField(
            model_name="searchexport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.OrganizationUser",
            ),
        )
    ]
