# Generated by Django 2.2.6 on 2019-12-03 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0006_auto_20191123_0053_squashed_0007_auto_20191123_0057")
    ]

    operations = [
        migrations.RemoveField(model_name="searchexport", name="charged"),
        migrations.RemoveField(model_name="searchexport", name="refunded"),
    ]
