# Generated by Django 2.2.6 on 2019-12-04 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("search", "0007_auto_20191203_2336")]

    operations = [
        migrations.RenameField(
            model_name="searchexport", old_name="valid_count", new_name="charged"
        )
    ]
