# Generated by Django 2.2.8 on 2020-01-07 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("search", "0008_auto_20191204_0636")]

    operations = [migrations.RemoveField(model_name="searchexport", name="charged")]
