# Generated by Django 2.2.8 on 2020-01-09 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("search", "0009_remove_searchexport_charged")]

    operations = [
        migrations.AlterField(
            model_name="searchexport",
            name="seat",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="users.Seat"
            ),
        )
    ]
