# Generated by Django 2.2.8 on 2020-01-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("search", "0010_auto_20200109_0256")]

    operations = [
        migrations.AddField(
            model_name="searchexport",
            name="is_removed",
            field=models.BooleanField(default=False),
        )
    ]
