# Generated by Django 2.2.8 on 2020-02-10 01:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0013_auto_20200120_2323"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchexportpage",
            name="progress_counter",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="WorkingExportRow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_id",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("data", django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_rows",
                        to="search.SearchExportPage",
                    ),
                ),
            ],
        ),
    ]
