# Generated by Django 2.2.8 on 2020-02-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0014_auto_20200210_0139"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchexportpage",
            name="pending_count",
            field=models.IntegerField(default=0, help_text="Number of tasks enqueued."),
        ),
        migrations.AlterField(
            model_name="searchexport",
            name="progress_counter",
            field=models.IntegerField(
                default=0, help_text="Number of profiles stored in completed pages."
            ),
        ),
        migrations.AlterField(
            model_name="searchexportpage",
            name="progress_counter",
            field=models.IntegerField(
                default=0, help_text="Number of profiles completed and saved."
            ),
        ),
    ]
