# Generated by Django 2.2.8 on 2020-02-10 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0015_auto_20200210_0233"),
    ]

    operations = [
        migrations.RemoveField(model_name="searchexportpage", name="limit",),
    ]
