# Generated by Django 2.2.8 on 2020-02-26 01:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_auto_20200221_0914"),
        ("search", "0016_remove_searchexportpage_limit"),
    ]

    operations = [
        migrations.CreateModel(
            name="DerivationCache",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("profile_id", models.CharField(max_length=180)),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.Seat"
                    ),
                ),
            ],
            options={"unique_together": {("profile_id", "seat")},},
        ),
    ]
