# Generated by Django 2.2.8 on 2020-04-15 23:36

from django.db import migrations, models
import django.db.models.deletion


def convert_seat_to_billing(apps, schema_editor):
    SearchExport = apps.get_model("search", "searchexport")
    for export in SearchExport.objects.filter(seat__isnull=False):
        export.billing_seat = export.seat.billing
        export.save(update_fields=["billing_seat"])


def convert_billing_to_seat(apps, schema_editor):
    SearchExport = apps.get_model("search", "searchexport")
    for export in SearchExport.objects.filter(billing_seat__isnull=False):
        export.seat = export.billing_seat.seat
        export.save(update_fields=["seat"])


def convert_derivation_seat_to_billing(apps, schema_editor):
    Model = apps.get_model("search", "derivationcache")
    for inst in Model.objects.all():
        inst.billing_seat = inst.seat.billing
        inst.save(update_fields=["billing_seat"])


def convert_derivation_billing_to_seat(apps, schema_editor):
    Model = apps.get_model("search", "derivationcache")
    for inst in Model.objects.all():
        inst.seat = inst.billing_seat.seat
        inst.save(update_fields=["seat"])


class Migration(migrations.Migration):

    replaces = [
        ("search", "0019_searchexport_billing_seat"),
        ("search", "0020_auto_20200313_1100"),
        ("search", "0021_derivationcache_billing_seat"),
        ("search", "0022_auto_20200313_1131"),
        ("search", "0023_auto_20200313_1220"),
        ("search", "0024_auto_20200313_1221"),
    ]

    dependencies = [
        ("search", "0026_auto_20200413_1624"),
        ("payments", "0015_wkplanpreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchexport",
            name="billing_seat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.BillingAccountMember",
            ),
        ),
        migrations.RunPython(
            code=convert_seat_to_billing, reverse_code=convert_billing_to_seat,
        ),
        migrations.AddField(
            model_name="derivationcache",
            name="billing_seat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.BillingAccountMember",
            ),
        ),
        migrations.RunPython(
            code=convert_derivation_seat_to_billing,
            reverse_code=convert_derivation_billing_to_seat,
        ),
        migrations.AlterField(
            model_name="derivationcache",
            name="billing_seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.BillingAccountMember",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="derivationcache", unique_together={("profile_id", "billing_seat")},
        ),
        migrations.RemoveField(model_name="derivationcache", name="seat",),
    ]
