# Generated by Django 2.2.8 on 2020-03-13 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0022_auto_20200313_1131"),
    ]

    operations = [
        migrations.AlterField(
            model_name="derivationcache",
            name="billing_seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.BillingAccountMember",
            ),
        ),
        migrations.AlterField(
            model_name="derivationcache",
            name="seat",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="users.Seat"
            ),
        ),
    ]
