# Generated by Django 2.2.8 on 2020-04-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0024_auto_20200313_1221"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchexport",
            name="csv",
            field=models.FileField(blank=True, null=True, upload_to="downloads"),
        ),
        migrations.AddField(
            model_name="searchexport",
            name="pre_validation_file",
            field=models.FileField(
                blank=True, editable=False, null=True, upload_to="validate"
            ),
        ),
    ]
