# Generated by Django 2.2.8 on 2020-04-17 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0026_auto_20200413_1624"),
        ("search", "0024_auto_20200313_1221"),
    ]

    operations = []
