# Generated by Django 2.2.8 on 2020-04-21 01:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0027_auto_20200418_2002"),
        ("search", "0027_merge_20200416_2053"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchProfileActionResult",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("group_task_id", models.CharField(max_length=255)),
                ("results", django.contrib.postgres.fields.jsonb.JSONField()),
                ("size", models.IntegerField(default=0)),
                (
                    "billing_seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.BillingAccountMember",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
