# Generated by Django 2.2.10 on 2020-05-05 00:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0028_batchprofileactionresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchexport",
            name="extra_columns",
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
