# Generated by Django 2.2.8 on 2020-04-21 01:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
import tagulous.models.fields



class Migration(migrations.Migration):

    dependencies = [
        ("search", "0030_auto_20200527_1300"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilterValueList",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "billing_seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.BillingAccountMember",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255)
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(max_length=255)
                ),
                (
                    "tags",
                    tagulous.models.fields.TagField(
                        _set_tag_meta=True,
                        force_lowercase=True,
                        help_text="Enter a comma-separated tag string",
                        to="coldemail.ColdEmailTagModel",
                    ),
                ),
                (
                    "values",
                    django.contrib.postgres.fields.jsonb.JSONField()
                ),
            ],
            options={"abstract": False,},
        ),
    ]
