# Generated by Django 2.2.10 on 2020-08-28 19:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coldemail', '0021_auto_20200706_1326'),
        ('payments', '0032_auto_20200706_1326'),
        ('search', '0030_auto_20200527_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterValueList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.CharField(blank=True, default='', max_length=255)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('billing_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.BillingAccountMember')),
                ('tags', tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', to='coldemail.ColdEmailTagModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
