# Generated by Django 2.2.10 on 2020-11-02 19:04

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0031_filtervaluelist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filtervaluelist",
            name="tags",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                blank=True,
                force_lowercase=True,
                help_text="Enter a comma-separated tag string",
                to="coldemail.ColdEmailTagModel",
            ),
        ),
    ]
