# Generated by Django 2.2.19 on 2021-04-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0033_searchexport_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchexport",
            name="rows_uploaded",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="searchexport",
            name="progress_counter",
            field=models.IntegerField(
                default=0, help_text="Number of profiles stored in completed pages"
            ),
        ),
    ]
