# Generated by Django 2.2.19 on 2021-04-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0034_auto_20210415_1539"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchexport",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Created"),
                    (2, "Pages Generating"),
                    (3, "Pages Running"),
                    (4, "Pages Complete"),
                    (8, "Awaiting External Validation"),
                    (16, "Validation Complete"),
                    (32, "Post Processing Hooks Done"),
                    (128, "Export Complete"),
                ],
                db_index=True,
                default=0,
                verbose_name="status",
            ),
        ),
    ]
