# Generated by Django 2.2.19 on 2021-07-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0036_auto_20210701_1028"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuerySource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cls", models.CharField(blank=True, default="", max_length=255)),
                ("object_id", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={"managed": False,},
        ),
    ]
