# Generated by Django 2.2.19 on 2021-07-16 18:02

from django.db import migrations, models
import whoweb.search.models.export


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0037_querysource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchexport",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "CREATED"),
                    (2, "PAGES_WORKING"),
                    (4, "PAGES_COMPLETE"),
                    (8, "VALIDATING"),
                    (16, "VALIDATED"),
                    (32, "POST_PROCESSED"),
                    (128, "COMPLETE"),
                ],
                db_index=True,
                default=whoweb.search.models.export.SearchExport.ExportStatusOptions(0),
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="searchexportpage",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "CREATED"), (2, "WORKING"), (4, "COMPLETE")],
                default=whoweb.search.models.export.SearchExportPage.PageStatusOptions(
                    0
                ),
                verbose_name="status",
            ),
        ),
    ]
