# Generated by Django 2.2.19 on 2021-09-11 01:26

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0038_auto_20210716_1102"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workingexportrow",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
